### ISSUE TITLE
Publish library to Maven central

### ISSUE THREAD

**Issue by ewiner** [BlockScore/blockscore-java#1]
`blockscore-java` would be much easier to integrate into a project if it were available on the central repos with everything else.

**Comment by alainmeier** [comment]
Hi @ewiner, what do you mean by on the central repos exactly?

**Comment by ewiner** [comment]
Just like Node has npm & Ruby has rubygems.org, most Java libraries are published to [Maven Central](http://central.sonatype.org/).  It's where you're getting your dependencies from in `build.gradle`.  A few changes to that file would let you run a 'publish' step where you could put official releases in the same place, so everyone else could get them easily without having to download and manage individual JARs.

Unfortunately I'm not familiar with your build tool, Gradle - but it's a pretty popular tool so finding information on publishing to the central repos shouldn't be too difficult.

**Comment by alainmeier** [comment]
Ah I understand what you mean. Yes, good idea, we will add `blockscore-java` to Maven.

**Comment by dgollahon** [comment]
We've just released a new version of the Java wrapper: https://github.com/BlockScore/blockscore-java/releases/tag/v4.0.0. It is available on Maven Central (see the README). This version is for Blockscore API version 4.0 (http://docs.blockscore.com/v4.0/java).
