### ISSUE TITLE
DatatypeConverter error

### ISSUE THREAD

**Issue by saintjab** [BlockScore/blockscore-java#10]
I was checking out the Java library and got this error on the line: `Person person = builder.create();`
The error is: Failed resolution of: Ljavax/xml/bind/DatatypeConverter
Thanks

**Comment by dgollahon** [comment]
This issue has been open a very long time, so I suspect you may have worked around it by now.

If you are still having trouble and can provide a small reproduction case, I can probably briefly look into this, but as it stands right now I don't know how to reproduce it and have not heard other complaints, so I'm going to close the issue. Feel free to comment if you need it re-opened.
