### ISSUE TITLE
Person.status is private

### ISSUE THREAD

**Issue by dmohs** [BlockScore/blockscore-java#11]
It seems like this is unintentional, since this is a useful rollup of the verification result. Perhaps there should be a `Person.getStatus()` method?

**Comment by dgollahon** [comment]
Hi @dmohs - good question. There is an `isValid()` method that you can use instead which returns `true` when `status` is `'valid'` and `false` otherwise. Hope that helps!

**Comment by dmohs** [comment]
Yep, I totally missed that. I converted our usage and it works great now. Thanks a ton and sorry for the noise.

**Comment by dgollahon** [comment]
No problem--sorry if the name wasn't obvious. Glad I could help!
