### ISSUE TITLE
Deserialization issue

### ISSUE THREAD

**Issue by alainmeier** [BlockScore/blockscore-java#13]
>The issue I now have is that the Blockscore Java sdk's jackson converter expects dates to come back from BlockScore with padded zeroes (e.g. April is "04" not just "4"), but John Bredenkamp's date of birth comes back without zero padding (i.e. 1940-8-11). This causes an error in deserializing the "com.blockscore.models.WatchlistHit" object.

<img width="1677" alt="screen-shot-2018-11-12-at-10-33-44-am" src="https://user-images.githubusercontent.com/138621/48361320-20670b00-e656-11e8-8bb8-41d1afc15f4a.png">

**Comment by dgollahon** [comment]
This problem is actually due to the fact that we incorrectly serialize some dates server side. I've pushed out a fix so that all values in the `date_of_birth` field should be valid, complete, iso8601 formatted dates.
